company_profile_task:
  description: >
    Leveraging all available AI agents and tools, create a company profile for {company}.
    Make sure to include the company's mission, vision, values, and any other relevant information.
  expected_output: >
    A comprehensive company profile for {company}, leveraging insights from all available AI agents, 
    formatted as markdown without '```'
  agent: company_profile_analyst

financial_task:
  description: >
    Leveraging all available AI agents and tools, create a financial report for {company}.
    Make sure to include the company's financial statements, ratios, and any other relevant information.
  expected_output: >
    A comprehensive financial report for {company}, leveraging insights from all available AI agents, 
    formatted as markdown without '```'
  agent: financial_analyst

# job_tech_task:
#   description: >
#     Leveraging all available AI agents and tools, create a job description for a {job_title} position
#      at {company}.
#     Make sure to include the job's responsibilities, requirements, and any other relevant information.
#   expected_output: >
#     A detailed job description for a {job_title} position at {company}, leveraging all available AI 
#     agents, formatted as markdown without '```'
#   agent: job_tech_analyst

industry_innovation_task:
  description: >
    Leveraging all available AI agents and tools, collect patents and industry insights for {company}
    Make sure to include the industry's trends, innovations, and any other relevant information.
  expected_output: >
    A comprehensive industry innovation report for {company}, leveraging insights from all available 
    AI agents, formatted as markdown without '```'
  agent: industry_innovation_analyst

competitor_mapping_task:
  description: >
    Leveraging all available AI agents and tools, map {company}'s top competitors, including a
     brief SWOT analysis and market positioning.
  expected_output: >
    A comprehensive competitor mapping report for {company}, including SWOT, market positioning,
     methodology, and sources, leveraging all available AI agents, formatted as markdown without '```'
  agent: competitor_mapping_analyst

social_media_sentiment_task:
  description: >
    Leveraging all available AI agents and tools, analyze public sentiment and mentions of {company}
     across major social media platforms 
    (e.g., Twitter, LinkedIn, Reddit).
  expected_output: >
    A comprehensive social media sentiment report for {company}, including key metrics, trends,
     and sources, leveraging all available AI agents, formatted as markdown without '```'
  agent: social_media_analyst

regulatory_overview_task:
  description: >
    Leveraging all available AI agents and tools, summarize {company}'s regulatory and compliance 
    landscape, including recent filings,
     lawsuits, and industry regulations.
  expected_output: >
    A comprehensive regulatory overview for {company}, with citations and leveraging all available 
    AI agents, formatted as markdown without '```'
  agent: regulatory_analyst

cyber_threat_snapshot_task:
  description: >
    Leveraging all available AI agents and tools, provide a snapshot of {company}'s cyber risk profile, 
    including breach history 
    and exposed credentials.
  expected_output: >
    A comprehensive cyber threat snapshot for {company}, including breach history, exposed credentials, 
    and sources, leveraging all available AI agents, formatted as markdown without '```'
  agent: cyber_threat_analyst

reporter_task:
  description: >
    Leveraging all available AI agents and tools, coordinate the tasks for the team.
    Make sure to assign tasks to team members and ensure timely completion.
  expected_output: >
    Compile a comprehensive OSINT report for {company}, compiled using outputs from all AI agents, 
    formatted as HTML in French
  agent: reporting_analyst
