version: '3.8'

services:
  streamlit:
    image: fjacquet/epic-news-streamlit:latest
    container_name: epic-news-streamlit
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./.env:/app/.env
      - ./db:/app/db
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # Add API_URL environment variable to connect to an external API
      - API_URL=${API_URL:-http://localhost:8000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: epic-news-network
    driver: bridge

volumes:
  db_data:
  app_data:
  app_output:
