version: '3.8'

services:
  api:
    image: fjacquet/epic-news-api:latest
    container_name: epic-news-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./db:/app/db
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: epic-news-network
    driver: bridge

volumes:
  db_data:
  app_data:
  app_output:
