version: '3.8'

services:
  api:
    image: fjacquet/epic-news-api:latest
    container_name: epic-news-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./db:/app/db
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - epic-news-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  streamlit:
    image: fjacquet/epic-news-streamlit:latest
    container_name: epic-news-streamlit
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./.env:/app/.env
      - ./db:/app/db
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - epic-news-network
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  epic-news-network:
    driver: bridge

volumes:
  db_data:
  app_data:
  app_output:
