[project]
name = "epic_news"
version = "0.1.0"
description = "epic-news using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "chromadb>=0.5.23",
    "composio-crewai>=0.7.18",
    "coverage>=7.9.1",
    "crewai>=0.130.0",
    "crewai-tools[mcp]>=0.47.1",
    "firecrawl-py>=2.8.0",
    "langchain-community>=0.3.25",
    "pandas>=2.3.0",
    "pytest>=8.4.0",
    "pytest-cov>=6.2.1",
    "python-dotenv>=1.1.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "ruff>=0.11.13",
    "serpapi>=0.1.5",
    "tavily-python>=0.7.6",
    "weasyprint>=65.1",
    "yfinance>=0.2.63",
]

[project.scripts]
kickoff = "epic_news.main:kickoff"
plot = "epic_news.main:plot"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "flow"
