saint_research_task:
  agent: saint_researcher
  description: >
    MANDATORY: Research the saint of the day in Switzerland for today's date (2025-06-23).
    
    STEP 1: Use WikipediaSearchTool to search for "saint of the day June 23", "calendrier liturgique 23 juin",
    "saint 23 juin", and related terms to identify today's saint.
    
    STEP 2: Once you identify the saint(s) for today, use WikipediaArticleTool to get detailed information
    about their life, significance, feast day, miracles, and any connection to Switzerland or the Catholic Church.
    
    STEP 3: Use SerperDevTool to search for additional information about today's saint, particularly
    any Swiss connections, local traditions, or celebrations.
    
    STEP 4: Use SaveToRagTool to store all your research findings for future reference.
    
    Focus on finding comprehensive information about the saint celebrated on June 23rd in the Catholic calendar.
  expected_output: >
    A detailed research report in French containing:
    - The name of the saint(s) celebrated on June 23rd
    - Complete biographical information
    - Significance and feast day details
    - Any miracles or notable events
    - Connection to Switzerland or Swiss Catholic traditions
    - Sources and references used
    Format as structured text with clear sections.
  async_execution: true
  output_file: output/saint_daily/research.md

saint_report_generation_task:
  agent: reporting_specialist
  description: >
    CRITICAL: Create a comprehensive HTML report in French about today's saint using the ReportingTool.
    
    STEP 1: Review all the research findings from the context about today's saint.
    
    STEP 2: Use the ReportingTool to generate a professional HTML report in French with the title
    "Saint du Jour - 23 Juin 2025" and comprehensive content about the saint.
    
    STEP 3: The report must include:
    - Title and introduction in French
    - Biography of the saint (Biographie)
    - Significance and feast day (Signification et Fête)
    - Miracles and notable events (Miracles et Événements Notables)
    - Connection to Switzerland (Lien avec la Suisse)
    - Prayer or reflection (Prière ou Réflexion)
    - Sources (Sources)
    
    STEP 4: Ensure the report is entirely in French, well-formatted, and uses appropriate religious terminology.
    
    The final output must be a complete HTML document generated using the ReportingTool.
  expected_output: >
    A complete, professional HTML report in French about today's saint, generated using the ReportingTool.
    The report must be comprehensive, well-structured, and entirely in French with proper Catholic terminology.
    NO raw data, NO placeholder text, ONLY a complete HTML document.
  async_execution: false
  output_file: output/saint_daily/report.html
