---
saint_research_task:
  agent: saint_researcher
  description: >
    Research comprehensive information about today's saint ({current_date}) using
    Wikipedia and web search tools.
    Find detailed information about:
    - The name of the saint(s) celebrated on {current_date}
    - Complete biographical information (birth, death, life events)
    - Significance and feast day details
    - Any miracles or notable events associated with the saint
    - Connection to Switzerland or Swiss Catholic traditions
    - Historical context and importance
    - Sources and references
    Provide thorough, accurate research that will be used to create a comprehensive
    HTML report.
    Include specific dates, places, and historical details when available.
  expected_output: >
    Comprehensive research report with detailed information about today's saint,
    including biographical details, significance, miracles, Swiss connections,
    and reliable sources. Format as structured text with clear sections.
  async_execution: false
saint_data_task:
  agent: saint_reporter
  description: >
    Génère des données structurées en JSON pour le rapport quotidien du saint.
    Utilise les informations de recherche du contexte pour créer un objet JSON avec
    la structure suivante :
    {
      "saint_name": "[Nom du saint]",
      "feast_date": "[Date de la fête]",
      "biography": "[Biographie détaillée du saint]",
      "significance": "[Signification et importance de ce saint]",
      "miracles": "[Miracles et événements notables]",
      "swiss_connection": "[Lien avec la Suisse si applicable]",
      "prayer_reflection": "[Prière ou réflexion spirituelle]",
      "sources": ["[Source 1]", "[Source 2]"],
      "birth_year": "[Année de naissance si connue]",
      "death_year": "[Année de décès si connue]",
      "patron_of": "[Patron de quoi/qui]"
    }
    IMPORTANT :
    - Utilise un français correct et respectueux
    - Inclus des informations historiques précises
    - Génère UNIQUEMENT le JSON, pas de texte supplémentaire
    - Les données seront utilisées par HtmlDesignerCrew pour générer le HTML final
  expected_output: >
    Objet JSON structuré contenant toutes les données du saint :
    - Nom, date de fête, biographie complète
    - Signification, miracles, lien avec la Suisse
    - Prière/réflexion et sources fiables
    - Format JSON pur, prêt pour le rendu HTML unifié
  context: [saint_research_task]
  output_file: '{output_file}'
  async_execution: false
