

extract_special_needs_task:
  description: >
    Analyze the provided user request: "{user_request}" and extract any special travel needs mentioned.
    
    Special travel needs include but are not limited to:
    - Discount cards (senior, student, youth, etc.)
    - Frequent traveler cards or loyalty programs
    - Special accessibility requirements
    - Special meal preferences
    - Travel insurance requirements
    - Special luggage requirements
    - Preferred transportation services
    
    For example:
    - From "I need to book a trip to Paris using my Eurail pass" → "Eurail pass"
    - From "Plan a journey to London with my senior discount card" → "senior discount card"
    - From "I want to use my frequent flyer miles for a trip to Tokyo" → "frequent flyer miles"
    
    If no special needs are mentioned, respond with "No special needs mentioned".
  expected_output: >
    Return ONLY the special needs as a concise phrase, with no additional explanation, 
    formatting, or context. Output should not include any prefixes or punctuation at the end.
  agent: special_needs_extractor
