---
intelligence_requirements_planning:
  description: >
    Develop comprehensive intelligence requirements for investigating
    {target}, including: 
    - Priority information needs 
    - Key intelligence questions 
    - Collection priorities by domain 
    - Timeline for intelligence gathering 
    - Critical information gaps 
    - Success criteria for the investigation
    Format your planning as a structured JSON object.
  expected_output: >
    A comprehensive JSON object outlining intelligence requirements for
    investigating {target}. The JSON should be well-structured with appropriate keys and values.
  agent: osint_researcher
  output_file: output/osint/intelligence_requirements_planning.json
intelligence_collection_coordination:
  description: >
    Coordinate intelligence collection activities across all specialized crews
    investigating {target}, including: 
    - Tasking specialized crews based on intelligence requirements 
    - Tracking collection progress against requirements 
    - Identifying collection gaps and redundancies 
    - Adjusting collection priorities as new information emerges 
    - Ensuring comprehensive coverage across all domains 
    - Facilitating information sharing between crews
    Format your coordination notes as a structured JSON object.
  expected_output: >
    A comprehensive JSON object detailing intelligence collection
    coordination for {target}. The JSON should be well-structured with appropriate keys and values.
  agent: osint_researcher
  output_file: output/osint/intelligence_collection_coordination.json
intelligence_analysis_integration:
  description: >
    Integrate intelligence analysis from all specialized crews investigating
    {target}, including: 
    - Synthesizing findings across domains 
    - Identifying cross-domain patterns and insights 
    - Resolving contradictory information 
    - Validating key findings through multiple sources 
    - Contextualizing intelligence within the broader picture 
    - Developing integrated assessments
    Format your integrated analysis as a structured JSON object.
  expected_output: >
    A comprehensive JSON object integrating intelligence analysis from all
    crews investigating {target}. The JSON should be well-structured with appropriate keys and values.
  agent: osint_researcher
  output_file: output/osint/intelligence_analysis_integration.json
intelligence_product_development:
  description: >
    Develop final intelligence products about {target}, including:  
    - Executive summary for decision-makers 
    - Comprehensive intelligence report 
    - Key findings and assessments 
    - Supporting evidence and documentation 
    - Confidence levels for major assessments 
    - Recommendations for further investigation
    Format your intelligence products as a structured JSON object.
  expected_output: >
    A comprehensive JSON object serving as final intelligence
    products about {target}. The JSON should be well-structured with appropriate keys and values.
  agent: osint_researcher
  output_file: output/osint/intelligence_product_development.json
# investigation_quality_assurance:
#   description: >
#     Conduct quality assurance review of the entire investigation of {target},
#     including: 
#     - Verification of key facts and findings 
#     - Assessment of source reliability and credibility 
#     - Identification of analytical biases or gaps
#     - Evaluation of intelligence product quality 
#     - Documentation of lessons learned 
#     - Recommendations for process improvements
#     Use the RAG tools to retrieve all relevant information, analysis, and
#     products and conduct a thorough quality assurance review. Format your QA
#     review in a clear, structured HTML document.
#   expected_output: >
#     A comprehensive HTML document in french,containing a thorough quality assurance
#     review of the investigation of {target}, with proper formatting, headings,
#     and organization. Save your QA review to the RAG database.
#   agent: osint_coordinator
#   output_file: "output/osint/investigation_quality_assurance.html"
global_reporting:
  description: >
    Create a comprehensive and extensive global intelligence report on {target} by
     aggregating all information from the 'output/osint' directory.
    This report must be extremely detailed and maintain the full depth of 
    information from all source reports, including:
    - A thorough executive summary capturing all key findings
    - Exhaustive presentation of all intelligence gathered, maintaining the original
    level of detail
    - A highly structured organization with clear sections and subsections
    - Complete representation of all technical details, statistics, and specialized
    information
    - Preservation of all nuances, context, and supporting evidence from source materials
    Your process to generate this report is CRITICAL and MUST be followed EXACTLY:
    1. First, use the `directory_read_tool` specifically on the 'output/osint' directory.
     This will give you a list of filenames of the previously generated reports.
    2. Second, for EACH AND EVERY filename obtained in step 1, you ABSOLUTELY MUST
     use the `file_read_tool` to read the FULL TEXTUAL CONTENT of that specific file.
     Do not summarize or list the files at this stage; your goal is to gather all
    the raw information from within them.
    3. Third, after you have successfully read the content from ALL files, your primary task
    is to SYNTHESIZE this collected textual information. Create a single, coherent,
     and comprehensive global intelligence report. This report is NOT a list of files,
     nor a summary of what files exist. It is an INTEGRATION of the INFORMATION CONTAINED
    WITHIN those files.
    4. DO NOT HALLUCINATE. Do not invent file counts or content. Base your report strictly
    on the actual content retrieved using the `file_read_tool`.
    5. The final report should be a structured JSON object that integrates the information
    from the files, not a meta-report about the files themselves or a simple concatenation.
  expected_output: >
    A comprehensive and extensive global intelligence report in a well-structured JSON format.
    The report must provide a complete synthesis of all gathered intelligence
    on {target} with appropriate keys and values.
  agent: osint_reporter
  output_file: output/osint/global_report.json
