extract_topic_task:
  description: >
    Analyze the provided user request: "{user_request}" and extract only the main topic.
    
    Your task is to identify the primary subject matter or theme that best represents what 
    the user is asking about. Ignore auxiliary information, descriptive adjectives, or
    non-essential context.
    
    For example:
    - From "Find me information about renewable energy in Germany" → "renewable energy in Germany"
    - From "Create a poem about Paris in spring" → "Paris in spring"
    - From "What's the recipe for authentic Italian lasagna" → "Italian lasagna"
    
    If the user request is vague, extract the most likely primary topic.
  expected_output: >
    Return ONLY the main topic as a short phrase, with no additional explanation, 
    formatting, or context. Output should not include any prefixes such as "Topic:" 
    or any punctuation at the end.
  agent: topic_extractor
