research_company_task:
  description: >
    Conduct thorough research on {company}. Focus on their industry,
    size, recent news, challenges they might be facing, and any information
    that suggests they might benefit from {our_product}. Look for recent
    technology initiatives or digital transformation efforts.
    You are AI agent that is responsible for taking actions based on the tools you have.
  expected_output: >
    A comprehensive overview of {company}, including key facts,
    recent developments, and potential pain points that our product could address.

analyze_org_structure_task:
  description: >
    Analyze the organizational structure of {company}. Identify key
    departments and roles that are likely to be involved in decisions related
    to purchasing {our_product}. Consider both technical decision-makers and
    business stakeholders.
    You are AI agent that is responsible for taking actions based on the tools you have.
  expected_output: >
    A breakdown of {company}'s relevant organizational structure,
    highlighting departments and roles that are potential stakeholders for
    {our_product}.

find_key_contacts_task:
  description: >
    Based on the organizational analysis, identify specific individuals at
    {company} who are in positions to influence or make decisions about
    purchasing {our_product}. Find their names, titles, and if possible,
    professional contact information or LinkedIn profiles.
  expected_output: >
    A list of key contacts at {company}, including their names, titles,
    departments, and any available contact information, LinkedIn URLs if possible phones and emails.

develop_approach_strategy_task:
  description: >
    Using all the gathered information about {company} and the identified
    contacts, develop a strategy for approaching these individuals about
    {our_product}. Consider the company's challenges, the contacts' roles,
    and how our product can provide value to them.
    You are AI agent that is responsible for taking actions based on the tools you have.
    REMOVE ANY COMMENT OR THINGS LIKE "my best complete final answer to the task"
  expected_output: >
    A ContactFinderResult object containing:
    1. A concise company overview
    2. A list of key contacts with their information
    3. A tailored approach strategy for reaching out to these contacts about {our_product}
    Must be HTML-formatted for easy reading and sharing with the sales team with relevant emojis.
    Must be in French.
