---
research_task:
  description: >
    Conduct thorough research on {company}, their position in the sector, and
    recent industry trends. Focus on news from the last year, as the current
    year is 2024.
    Take into account any information from prior interactions:
    {prior_interactions}
    Participants {participants} Meeting Context {context}
  expected_output: >
    A comprehensive report on {company}'s background, their status in the
    sector, and relevant industry insights. Include a list of 10 bullet points
    highlighting the most crucial information for our meeting and a detailed
    report summarizing key findings about each participant
  agent: lead_researcher_agent
product_alignment_task:
  description: >
    Analyze the current industry trends, challenges, and opportunities
    relevant to the meeting's context. Consider market reports, recent
    developments, and expert opinions to provide a comprehensive overview of
     the industry landscape.
    Also provide a list of 10 bullet points highlighting the most crucial
    information for our meeting. We need if possible supporting documents to
    justify your analysis.
    Consider any insights from prior interactions - {prior_interactions}
    Participants {participants} Meeting Context {context}
  expected_output: >
    An insightful analysis that identifies major trends, potential challenges,
    and strategic opportunities
  agent: product_specialist_agent
sales_strategy_task:
  description: >
    Develop a tailored sales approach for {company}. Consider their position
    in the  sector, company size, and potential objections. Prepare strategies
    for handling these objections and identify potential upselling or
    cross-selling opportunities. Develop strategic talking points, questions,
    and discussion angles for the meeting based on the research and industry
    analysis conducted.
    Factor in any insights from {prior_interactions} Meeting Context:
    {context} Meeting Objective: {objective}
  agent: sales_strategist_agent
  expected_output: >
    A comprehensive sales strategy document including approach, objection
    handling techniques, and additional sales opportunities tailored for the
    meeting with from {company}.
meeting_preparation_task:
  description: >
    Compile all the research findings, industry analysis, and strategic
    talking points into a concise, comprehensive briefing document for the
    meeting with {company}. Ensure the briefing is easy to digest and equips
    the meeting participants with all necessary information and strategies.
    Meeting Context {context} Meeting Objective {objective} Incorporate any
    relevant points from prior interactions {prior_interactions}
    IMPORTANT: Format the output as a structured JSON document to ensure it can be
    processed programmatically. The JSON should have the following key sections:
    - "title": The title of the meeting briefing
    - "summary": Brief overview of the meeting purpose
    - "company_profile": Key information about the company
    - "participants": List of participant bios
    - "industry_overview": Industry analysis and context
    - "talking_points": Key topics for discussion
    - "strategic_recommendations": Action items and strategic suggestions
    - "additional_resources": Any reference materials or links
  expected_output: >
    A comprehensive, well-structured JSON document in French for the meeting with
    {company}.
    The output MUST be valid, properly formatted JSON only. Do NOT include any markdown,
    introductory text, explanations, or backticks outside of the actual JSON content.
    Example structure:
    {
      "title": "Réunion Stratégique avec {company}",
      "summary": "Aperçu de la réunion et objectifs principaux",
      "company_profile": {
        "name": "Nom de l'entreprise",
        "industry": "Secteur d'activité",
        "key_products": ["Produit 1", "Produit 2"],
        "market_position": "Description de la position sur le marché"
      },
      "participants": [
        {
          "name": "Nom du participant",
          "role": "Fonction",
          "background": "Informations pertinentes"
        }
      ],
      "industry_overview": "Analyse détaillée du secteur",
      "talking_points": [
        {
          "topic": "Sujet 1",
          "key_points": ["Point 1", "Point 2"],
          "questions": ["Question 1?", "Question 2?"]
        }
      ],
      "strategic_recommendations": [
        {
          "area": "Domaine d'action",
          "suggestion": "Suggestion détaillée",
          "expected_outcome": "Résultat attendu"
        }
      ],
      "additional_resources": [
        {"title": "Titre de la ressource", "description": "Description", "link": "URL"}
      ]
    }
  agent: briefing_coordinator_agent
  output_file: '{output_file}'
