research_task:
  description: >
    Conduct thorough research on {company}, their position in the sector,
    and recent industry trends. Focus on news from the last year, as the current
    year is 2024.

    Take into account any information from prior interactions: {prior_interactions}

    Participants {participants}
    Meeting Context {context}

  expected_output: >
    A comprehensive report on {company}'s background, their status in the
    sector, and relevant industry insights. Include a list of 10 bullet points
    highlighting the most crucial information for our meeting and a detailed report summarizing key findings about each participant


product_alignment_task:
  description: >
    Analyze the current industry trends, challenges, and opportunities
    relevant to the meeting's context. Consider market reports, recent
    developments, and expert opinions to provide a comprehensive overview of the industry landscape.

    Consider any insights from prior interactions - {prior_interactions}

    Participants {participants}
    Meeting Context {context}

  expected_output: >
    An insightful analysis that identifies major trends, potential
    challenges, and strategic opportunities


sales_strategy_task:
  description: >
    Develop a tailored sales approach for {company}. Consider their position in
    the  sector, company size, and potential objections. Prepare strategies
    for handling these objections and identify potential upselling or cross-selling
    opportunities. Develop strategic talking points, questions, and discussion angles
    for the meeting based on the research and industry analysis conducted.

    Factor in any insights from {prior_interactions}
    Meeting Context: {context}
    Meeting Objective: {objective}

  expected_output: >
    A comprehensive sales strategy document including approach, objection handling
    techniques, and additional sales opportunities tailored for the meeting with
    from {company}.


meeting_preparation_task:
  description: >
    Compile all the research findings, industry analysis, and strategic
    talking points into a concise, comprehensive briefing document for
    the meeting with {company}. Ensure the briefing is easy to digest and equips the meeting
    participants with all necessary information and strategies.

    Meeting Context {context}
    Meeting Objective {objective}
    Incorporate any relevant points from prior interactions {prior_interactions}

    IMPORTANT: Format the output as HTML to ensure it displays properly in email. 
    Use proper HTML structure with:
    - <h1>, <h2>, <h3> tags for headings
    - <p> tags for paragraphs
    - <ul> and <li> tags for bullet points
    - <table> for any tabular data
    - Proper spacing and formatting for readability
    - Include a title and summary at the top

    The document will be sent via email, so ensure it's properly formatted for email viewing.

  expected_output: >
    A comprehensive HTML-formatted briefing document with relevant emojis in french for the meeting with {company} that includes sections for meeting participant-only bios,
    industry overview, talking points, and strategic recommendations. The document should be structured in a logical
    and engaging manner to facilitate a productive and insightful meeting, and be properly formatted for email delivery.
  output_file: "output/meeting/meeting_preparation.md"
