product_research_task:
  description: >
    Conduct comprehensive research on the product: **{topic}** in {current_year}.
    Your primary objective is: **{objective}**.
    Focus on gathering detailed information about its features, technical specifications,
    user reviews (both positive and negative), expert opinions, and any known issues or recalls.
    Compile a detailed summary of your findings, which will serve as the foundation for the other agents.
    Save all findings to the RAG system for other agents to use.
    Make sure you find the most current and relevant information for {current_year}.
  expected_output: >
    A comprehensive research report containing:
    - Product overview with key specifications
    - Detailed list of pros and cons (at least 5 each)
    - Summary of user reviews and professional evaluations
    - Common issues and their solutions
    - Target audience and best use cases
    All information should be well-sourced and current.
  async_execution: true
  agent: product_researcher
  output_file: "output/shopping_advisor/product_research.md"

price_analysis_task:
  description: >
    Based on the research for **{topic}**, analyze its pricing in the Swiss and French markets in {current_year}. 
    Your analysis should include:
    - Current prices from major retailers in both countries
    - Direct purchase links for the best offers
    - Shipping costs and delivery times
    - Warranty and return policy information
    - Seasonal price trends and potential discounts
    - Total cost comparison including taxes and shipping

    Focus on these major retailers:
    - Switzerland: Digitec, Galaxus, Manor, Microspot, Interdiscount
    - France: Amazon.fr, Fnac, Cdiscount, Darty, Boulanger    
    Note any significant price differences, promotions, or bundle deals.
    Your objective is to provide a clear price comparison.
    Save all pricing information to the RAG system.
  expected_output: >
    A detailed price analysis report containing:
    - Current prices from at least 5 retailers per country
    - Direct purchase links for each offer
    - Total cost breakdown including shipping and taxes
    - Best value recommendations for each country
    - Price trend analysis and buying recommendations
  agent: price_analyst
  async_execution: true
  output_file: "output/shopping_advisor/price_analysis.md"

competitor_analysis_task:
  description: >
    Identify and analyze the main competitors to **{topic}** in {current_year}.
    Your analysis should include:
    - 3-5 main competing products with similar features
    - Feature-by-feature comparison
    - Price comparison across competitors
    - Pros and cons of each alternative
    - Market positioning and target audience differences
    - Unique selling points of each competitor
    
    Focus on direct competitors and alternative solutions that solve similar problems.
    Save all competitor information to the RAG system.
  expected_output: >
    A comprehensive competitor analysis containing:
    - List of 3-5 main competitors with detailed descriptions
    - Feature comparison matrix
    - Price comparison across all competitors
    - Strengths and weaknesses of each alternative
    - Market positioning analysis
    - Recommendations for different user needs
  async_execution: true
  agent: competitor_analyst
  output_file: "output/shopping_advisor/product_research.md"

shopping_advice_task:
  description: >
    Synthesize all the gathered information—product research, price analysis, and competitor analysis—for **{topic}**
    Create a comprehensive shopping advice report for {topic} that consolidates all research findings.
    Use the ReportingTool to generate a professional HTML report that includes:
    
    **Report Structure:**
    1. Executive Summary with key recommendations
    2. Product Overview and Specifications
    3. Detailed Pros and Cons Analysis
    4. Price Comparison (Switzerland vs France)
    5. Competitor Analysis with Comparison Table
    6. Final Recommendations and Purchase Links
    
    **Key Requirements:**
    - Use the knowledge base to retrieve all gathered information from previous tasks
    - Create professional comparison tables for features and prices
    - Include direct purchase links for best offers in both countries
    - Provide clear, actionable buying recommendations
    - Use proper HTML formatting with emojis for visual appeal
    - Ensure the report is comprehensive yet easy to read
    
    IMPORTANT: When calling the Professional Report Generator tool, you MUST use the exact output file path: "output/shopping_advisor/shopping_advice.html"
    DO NOT use any other filename or path. The tool requires three parameters:
    - report_title: "Shopping Advice Report"
    - report_body: [your complete HTML content]
    - output_file_path: "output/shopping_advisor/shopping_advice.html"

    The report should help users make an informed purchasing decision with all necessary information in one place.
  expected_output: >
    A complete, professional HTML shopping advice report in french generated using the ReportingTool containing:
    - Executive summary with clear recommendations
    - Comprehensive product analysis with pros/cons
    - Detailed price comparison tables for Switzerland and France
    - Competitor comparison matrix with features and pricing
    - Final recommendations with direct purchase links
    - Professional formatting with proper HTML structure and emojis
  agent: shopping_advisor
  output_file: "output/shopping_advisor/shopping_advice.html"