---
product_research_task:
  description: >
    Conduct comprehensive research on the product: **{topic}** in {current_year}.
    Additional context: {context}.
    Your primary objective is: **{objective}**.
    Focus on gathering detailed information about its features, technical specifications,  user
    reviews (both positive and negative), expert opinions, and any known issues or
    recalls.
    Compile a detailed summary of your findings, which will serve as the foundation
    for the other agents.
    Make sure you find the most current and relevant information for {current_year}.
  expected_output: >
    A comprehensive research report containing:
    - Product overview with key specifications
    - Detailed list of pros and cons (at least 5 each)
    - Summary of user reviews and professional evaluations
    - Common issues and their solutions
    - Target audience and best use cases
    All information should be well-sourced and current.
  async_execution: false
  agent: product_researcher
  output_file: output/shopping_advisor/product_research.md
price_analysis_task:
  description: >
    Based on the research for **{topic}**, analyze its pricing in the Swiss and French
    markets
    in {current_year}. Consider the context provided: {context}.
    Your analysis should include:
    - Current prices from major retailers in both countries
    - Direct purchase links for the best offers
    - Shipping costs and delivery times
    - Warranty and return policy information
    - Seasonal price trends and potential discounts
    - Total cost comparison including taxes and shipping
    Focus on these major retailers:
    - Switzerland: Digitec, Galaxus, Manor, Microspot, Interdiscount
    - France: Amazon.fr, Fnac, Cdiscount, Darty, Boulanger     Note any significant
    price differences, promotions, or bundle deals.
    Your objective is to provide a clear price comparison.
  expected_output: >
    A detailed price analysis report containing:
    - Current prices from at least 5 retailers per country
    - Direct purchase links for each offer
    - Total cost breakdown including shipping and taxes
    - Best value recommendations for each country
    - Price trend analysis and buying recommendations
  agent: price_analyst
  async_execution: false
  output_file: output/shopping_advisor/price_analysis.md
competitor_analysis_task:
  description: >
    Identify and analyze the main competitors to **{topic}** in {current_year},
    considering the context: {context}.
    Your analysis should include:
    - 3-5 main competing products with similar features
    - Feature-by-feature comparison
    - Price comparison across competitors
    - Pros and cons of each alternative
    - Market positioning and target audience differences
    - Unique selling points of each competitor
    Focus on direct competitors and alternative solutions that solve similar problems.
  expected_output: >
    A comprehensive competitor analysis containing:
    - List of 3-5 main competitors with detailed descriptions
    - Feature comparison matrix
    - Price comparison across all competitors
    - Strengths and weaknesses of each alternative
    - Market positioning analysis
    - Recommendations for different user needs
  async_execution: false
  agent: competitor_analyst
  output_file: output/shopping_advisor/product_research.md
shopping_data_task:
  description: >
    Based on all the research, price analysis, and competitor analysis for {topic},
    create a comprehensive structured shopping advice report in French.
    You MUST provide ALL of the following required fields:
    1. **product_info**: Complete product information with specifications, pros, and
    cons
    2. **switzerland_prices**: Detailed price information from Swiss retailers with
    direct links
    3. **france_prices**: Detailed price information from French retailers with direct
    links
    4. **competitors**: Comprehensive competitor analysis with feature comparisons
    5. **executive_summary**: Executive summary with clear recommendations (required
    field)
    6. **final_recommendations**: Final purchase recommendations with reasoning (required
    field)
    7. **best_deals**: Best deals and value propositions as a list of strings (required
    field)
    8. **user_preferences_context**: Summary of user preferences and constraints considered
    (required field)
    Consider the context: {context} and ensure all recommendations are practical
    and actionable for French-speaking users.
    Focus on providing complete, accurate, and well-structured data that matches
    the ShoppingAdviceOutput Pydantic model exactly.
  expected_output: >
    A comprehensive ShoppingAdviceOutput data structure containing ALL required fields:
    product_info, switzerland_prices, france_prices, competitors, executive_summary,
    final_recommendations, best_deals, and user_preferences_context.
    All data must be complete, accurate, and ready for HTML report generation.
  agent: shopping_advisor
  output_file: '{output_file}'
