---
analyze_market_task:
  description: >
    Analyser le message marketing original en français ci-dessous pour identifier
    les points forts
    et les opportunités d'amélioration:
    "{original_message}"
    Considérez les aspects suivants:
    - Clarté du message et proposition de valeur
    - Impact émotionnel et persuasion
    - Adaptation au public cible {target_audience}
    - Appel à l'action efficace
    Identifier au moins 5 points spécifiques à améliorer.
  expected_output: >
    Une analyse détaillée du message avec 5 points d'amélioration concrets et stratégiques.
  agent: marketing_specialist
  output_file: /output/marketing/analysis.json
enhance_message_task:
  description: >
    En vous basant sur l'analyse marketing, réécrivez et améliorez le message suivant
    en français  pour le rendre plus persuasif et attrayant pour le public cible {target_audience}:
    "{original_message}"
    Votre message amélioré doit:
    - Avoir un ton professionnel mais engageant
    - Inclure des formulations persuasives qui incitent à l'action
    - Mettre en valeur les bénéfices de façon plus convaincante
    - Utiliser un vocabulaire émotionnel adapté au public cible
    - Respecter la culture et les nuances linguistiques françaises
    - Oser les émojis
    - Être structuré avec un début accrocheur, un développement clair et une conclusion
    forte
  expected_output: >
    Le message marketing amélioré en français, optimisé pour générer plus d'engagement
    et de conversions.
  agent: copywriter
  output_file: '{output_file}'
