---
write_poem:
  description: >
    Write a poem about the topic: {topic}.
    The poem should be creative, engaging, and well-structured.
    Your final answer MUST be a JSON object with two keys: 'title' and 'poem'.
    Do not include any other text or formatting.
  expected_output: >
    A JSON object containing the title and the full text of the poem.
    Example:
    {
      "title": "Ode to a Sunset",
      "poem": "The sun dips low, a painter's final stroke..."
    }
  output_file: '{output_file}'
