
extract_origin_task:
  description: >
    Analyze the provided user request: "{user_request}" and extract the origin location of the travel.
    
    The origin is the starting point or departure location of the travel. It may be mentioned explicitly 
    or implied in the context of the request.
    
    For example:
    - From "I need to book a trip from New York to Paris" → "New York"
    - From "Plan a journey starting in London heading to Tokyo" → "London"
    - From "We're traveling from our home in San Francisco to visit relatives in Chicago" → "San Francisco"
    
    If no origin is mentioned or can be reasonably inferred, respond with "Montreux, Switzerland".
    
    If there are multiple possible origins mentioned (like in a multi-city trip), extract the initial starting point only.
  expected_output: >
    Return ONLY the origin location as a concise place name, with no additional explanation, 
    formatting, or context. Output should not include any prefixes or punctuation at the end.
  agent: origin_extractor
