research_task:
  description: >
    you are a placeholder, do nothing
  expected_output: >
    send ok message
  agent: researcher

reporting_task:
  description: >
    you are a placeholder, do nothing
  expected_output: >
    send ok message
  agent: reporting_analyst
