extract_travelers_task:
  description: >
    Analyze the provided user input: "{user_request}" and extract all information about the travelers.
    
    Focus on identifying:
    - Number of travelers
    - Ages or age categories (adults, children, seniors, infants, etc.)
    - Relationship between travelers (family, couple, friends, colleagues, etc.)
    - Any special requirements for specific travelers
    - Any other relevant traveler-specific details
    
    For example:
    - From "I need to book a trip for my family of 4 including 2 kids" → "Family of 4 (2 adults, 2 children)"
    - From "Planning a weekend trip with my partner" → "Couple (2 adults)"
    - From "Organizing a company retreat for 8 team members" → "Group of 8 colleagues"
    
    If no traveler information is specified, respond with "No traveler information specified".
  expected_output: >
    Return a concise description of the travelers, including number, relationships, and age categories 
    when available. Format should be simple and direct without additional explanations.
  agent: travelers_extractor
