
distribution_task:
  description: >
    Send an email to {recipient_email} with the EXACT content of {output_file} as the email body.
    
    IMPORTANT:
    1. Read the file {output_file} directly using os.path and open() functions
    2. Send the EXACT content as HTML in the email body, NOT as an attachment
    3. Do NOT rewrite or modify the content in any way
    4. Ensure content is in French as specified
    5. Do not use markdown formatting with ``` in the email
    
  expected_output: >
    1. The subject line used
    2. The recipient's email address ({recipient_email})
    3. The delivery status
    4. Confirmation that the EXACT file content was used
  agent: distributor
