research_destination:
  description: >
    Research all aspects of {destination} for a {duration} trip for {family}, including:
    - Suitability for {duration}
    - Attractions, activities, local culture, customs
    - Transportation from {origin} and within {destination}
    - Seasonal/weather considerations
    - Special needs: {special_needs}
  agent: travel_researcher
  expected_output: >
    Detailed research document covering all key aspects above, including practical logistics and unique appeal.

recommend_accommodation_and_dining:
  description: >
    Using the research, recommend:
    - 3-5 accommodations with details, prices, booking info, accessibility, value
    - Dining options for each day (breakfast, lunch, dinner), with names, cuisines, prices, addresses, and special needs
  agent: accommodation_specialist
  context: [research_destination]
  expected_output: >
    Detailed accommodation and dining plan, with all relevant info for the entire trip.

plan_itinerary:
  description: >
    Create a day-by-day itinerary that:
    - Organizes activities, meals, and logistics by day/time
    - Balances highlights and hidden gems
    - Considers family/special needs and practical constraints (openings, costs, bookings)
    - Includes local tips and flexibility
  agent: itinerary_architect
  context: [research_destination, recommend_accommodation_and_dining]
  expected_output: >
    Exhaustively detailed itinerary, with precise timing, locations, logistics, and descriptions for each element.

analyze_and_optimize_budget:
  description: >
    Review the itinerary and provide:
    - Detailed budget breakdown (accommodation, dining, activities, transport)
    - Value-maximizing recommendations and savings tips
    - Realistic cost estimates for all elements
  agent: budget_manager
  context: [plan_itinerary]
  expected_output: >
    Comprehensive budget report, with breakdowns, optimization, and value tips.

format_and_translate_guide:
  description: >
    Compile ALL previous outputs into a single, highly detailed travel guide:
    - Clean, professional HTML (not markdown)
    - All sections: intro, itinerary, accommodation, dining, activities, logistics, tips, budget, local insights
    - The guide must be written ONLY in impeccable French, preserving all detail and clarity
    - Use relevant emojis for clarity and engagement
  agent: content_formatter
  context: [research_destination, recommend_accommodation_and_dining, plan_itinerary, analyze_and_optimize_budget]
  expected_output: >
    Guide de voyage complet, exhaustif et détaillé, en HTML, rédigé uniquement en français, avec toutes les sections demandées et les emojis appropriés.