---
physical_location_mapping:
  description: >
    Map the physical locations of {company}, including:   - Headquarters and regional
    offices   - Manufacturing or production facilities   - Distribution centers and
    warehouses   - Retail locations (if applicable)   - Data centers and technical
    infrastructure   - Research and development facilities
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object mapping {company}'s physical locations.
    The JSON should be well-structured with appropriate keys and values.
  agent: geospatial_researcher
  output_file: output/osint/{company}_physical_location_mapping.json
geospatial_risk_assessment:
  description: >
    Assess geospatial risks for {company}'s locations, including:   - Natural disaster
    exposure   - Political stability in operating regions   - Infrastructure reliability
    by location   - Local regulatory environments   - Proximity to potential hazards   -
    Climate change impact projections
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object assessing geospatial risks for
    {company}. The JSON should be well-structured with appropriate keys and values.
  agent: geospatial_researcher
  output_file: output/osint/{company}_geospatial_risk_assessment.json
supply_chain_mapping:
  description: >
    Map {company}'s supply chain geospatially, including:   - Key supplier locations   -
    Transportation routes and logistics hubs   - Raw material sources   - Manufacturing
    partner locations   - Distribution networks   - Last-mile delivery infrastructure
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object mapping {company}'s supply chain
    geospatially. The JSON should be well-structured with appropriate keys and values.
  agent: geospatial_researcher
  output_file: output/osint/{company}_supply_chain_mapping.json
geospatial_intelligence_for_mergers_acquisitions:
  description: >
    Provide geospatial intelligence for {company}'s mergers and acquisitions,
    including:   - Geographic expansion patterns   - Location-based synergies with
    acquisition targets   - Regional market penetration strategies   - Post-acquisition
    geographic integration challenges   - Location-based competitive advantages   -
    Geographic diversification opportunities
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive data object providing geospatial intelligence for {company}'s
    M&A activities, conforming to the GeospatialAnalysisReport Pydantic model.
  agent: geospatial_reporter
  output_file: output/osint/{company}_geospatial_intelligence_for_mergers_acquisitions.json
