requirements_analysis_task:
  description: >
    Analyze the user's location request: "{user_request}".
    Identify specifically what type of location the user is looking for (restaurant, hotel, cafe, etc.).
    Extract key requirements such as preferred cuisine, price range, atmosphere, or any other specific criteria.
    Consider the topic "{topic}" as the main focus of the location search.
  expected_output: >
    A clear identification of:
    - The exact type of location being requested (restaurant, hotel, museum, etc.)
    - Specific criteria to filter options (cuisine type, price range, amenities, etc.)
    - Any other requirements that will help find precise location matches
  agent: location_requirements_analyst

location_research_task:
  description: >
    Based on the identified requirements, find exactly 5 specific location options that match the criteria.
    Focus solely on the specific type of location requested (restaurants, hotels, etc.) related to "{topic}".
    Do not research general area information or create a travel guide.
  expected_output: >
    A list of exactly 5 specific locations matching the requirements, with:
    - Name and precise location
    - Key features relevant to the request
    - What makes each option stand out
    - How well each matches the specific requirements in "{user_request}"
  agent: location_researcher

location_recommendation_task:
  description: >
    Create a focused report on the 5 specific locations found, with detailed information about each option.
    Do not include general area information, travel tips, or comprehensive guides.
    Focus only on the requested location type with specific, practical details about each option.
  expected_output: >
    A concise, focused guide with exactly 5 recommended options. For each option include:
    - Name and exact location
    - Key features
    - Why it matches the user's specific requirements
    - Relevant practical details (hours, prices, etc.)
    Format in French as HTML with relevant emojis, but keep it simple and focused.
  agent: location_recommendations_specialist
