---
tech_stack_identification:
  description: >
    Identify the technology stack used by {company}, including:  - Programming languages  -
    Frameworks and libraries  - Databases and data storage solutions  - Cloud services
    and hosting infrastructure  - DevOps tools and practices  - Front-end technologies  -
    Back-end technologies  - Mobile development technologies (if applicable)
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object identifying the technology stack of
    {company}. The JSON should be well-structured with appropriate keys and values.
  agent: tech_researcher
  output_file: output/osint/{company}_tech_stack_identification.json
tech_stack_analysis:
  description: >
    Analyze the technology stack of {company}, including:  - Strengths and weaknesses
    of their technical choices  - How their stack compares to industry standards and
    competitors  - Technical debt indicators  - Scalability and performance considerations  -
    Security implications  - Recent or planned technology migrations
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object analyzing the technology stack of
    {company}. The JSON should be well-structured with appropriate keys and values.
  agent: tech_researcher
  output_file: output/osint/{company}_tech_stack_analysis.json
open_source_contributions:
  description: >
    Research and analyze {company}'s open source contributions, including:  - GitHub
    repositories and activity  - Contributions to open source projects  - Technical
    blog posts and documentation  - Conference presentations and technical talks  -
    Developer advocacy initiatives
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object analyzing the open source contributions
    of {company}. The JSON should be well-structured with appropriate keys and values.
  agent: tech_researcher
  output_file: output/osint/{company}_open_source_contributions.json
tech_talent_assessment:
  description: >
    Assess the technical talent at {company}, including:  - Technical leadership profiles  -
    Engineering team structure and organization  - Technical hiring patterns and job
    requirements  - Technical skill sets emphasized in job postings  - Engineering
    culture indicators  - Technical career growth opportunities
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object assessing the technical talent at
    {company}. The JSON should be well-structured with appropriate keys and values.
  agent: tech_researcher
  output_file: output/osint/{company}_tech_talent_assessment.json
consolidate_tech_stack_report:
  description: >
    Consolidate all findings about {company}'s technology stack into a
    comprehensive report, including:  - Executive summary of technical capabilities  -
    Detailed technology stack breakdown  - Technical strengths and weaknesses  - Open
    source presence and contributions  - Technical talent assessment  - Recommendations
    for further technical investigation
    Format your report as a structured JSON object.
  expected_output: >
    A comprehensive data object consolidating all tech stack findings about {company},
    conforming to the TechStackReport Pydantic model.
  agent: tech_reporter
  output_file: output/osint/{company}_tech_stack_report.json
