leadership_team_assessment:
  description: >
    Assess the leadership team of {company}, including: - CEO and C-suite
    executives' backgrounds and experience - Leadership team stability and
    tenure - Leadership style and public communication - Board of directors
    composition and expertise - Leadership diversity metrics - Public
    perception of leadership

    Use the RAG tools to save your findings for later use by other agents.
    Format your findings in a clear, structured, and comprehensive Markdown
    document, ensuring all relevant details are included for a precise and
    extensive final report.
  expected_output: >
    A comprehensive Markdown document assessing {company}'s leadership team,
    with proper formatting, headings, and organization. The report should be
    as detailed and extensive as possible. Save your findings to the RAG
    database for use by other agents.
  agent: hr_intelligence_analyst
  output_file: output/osint/{company}_leadership_team_assessment.md

employee_sentiment_analysis:
  description: >
    Analyze employee reviews and sentiment about {company}, including: -
    Glassdoor, Indeed, and other review site analysis - Common themes in
    positive and negative reviews - Changes in sentiment over time -
    Comparison to industry benchmarks - Response patterns from company
    management - Employee satisfaction indicators

    Use the RAG tools to retrieve any relevant information already collected
    and save your findings for later use by other agents. Format your findings
    in a clear, structured, and comprehensive Markdown document, ensuring all
    relevant details are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document analyzing employee sentiment at
    {company}, with proper formatting, headings, and organization. The report
    should be as detailed and extensive as possible. Save your findings to the
    RAG database for use by other agents.
  agent: hr_intelligence_analyst
  output_file: output/osint/{company}_employee_sentiment_analysis.md

organizational_culture_assessment:
  description: >
    Assess the organizational culture of {company}, including: - Stated
    company values and their implementation - Work environment and practices -
    Recognition and reward systems - Communication and transparency -
    Innovation and adaptability indicators - Diversity, equity, and inclusion
    initiatives

    Use the RAG tools to retrieve any relevant information already collected
    and save your findings for later use by other agents. Format your findings
    in a clear, structured, and comprehensive Markdown document, ensuring all
    relevant details are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document assessing {company}'s organizational
    culture, with proper formatting, headings, and organization. The report
    should be as detailed and extensive as possible. Save your findings to the
    RAG database for use by other agents.
  agent: hr_intelligence_analyst
  output_file: output/osint/{company}_organizational_culture_assessment.md

talent_acquisition_strategy:
  description: >
    Analyze {company}'s talent acquisition strategy, including: - Job posting
    patterns and hiring focus areas - Recruitment methods and channels -
    Employer branding approach - Candidate experience indicators - Retention
    strategies and turnover patterns - Career development opportunities

    Use the RAG tools to retrieve any relevant information already collected
    and save your findings for later use by other agents. Format your findings
    in a clear, structured, and comprehensive Markdown document, ensuring all
    relevant details are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document analyzing {company}'s talent acquisition
    strategy, with proper formatting, headings, and organization. The report
    should be as detailed and extensive as possible. Save your findings to the
    RAG database for use by other agents.
  agent: hr_intelligence_analyst
  output_file: output/osint/{company}_talent_acquisition_strategy.md

format_hr_intelligence_report:
  description: >
    Consolidate all HR intelligence findings about {company} into a
    comprehensive report, including: - Executive summary of human capital
    insights - Leadership team assessment - Organizational culture analysis -
    Employee sentiment trends - Talent acquisition and retention strategies -
    Recommendations for further HR intelligence gathering

    Use the RAG tools to retrieve all previously collected information and
    create a consolidated, well-structured report. Format your report as a
    complete, comprehensive Markdown document, ensuring all relevant details
    are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document consolidating all HR intelligence
    findings about {company}, with proper formatting, headings, and
    organization. The report should be as detailed and extensive as possible.
    Save your consolidated report to the RAG database for use by other agents.
  agent: hr_intelligence_analyst
  output_file: output/osint/{company}_format_hr_intelligence_report.md
