---
classification_task:
  description: >
    Analyze the provided user request: "{user_request}" and classify it into
    the most appropriate category from the following options:
    {categories}
    Your task is to determine which specialized team should handle this
    request. Consider the content, intent, and subject matter of the request.
    IMPORTANT DISTINCTIONS:
    - COOKING: For requests about individual recipes, single dishes, specific cooking
    techniques, or ingredient-focused queries
    - MENU: For requests about meal planning, weekly menus, menu design, multiple
    recipes for a period, shopping lists, or dietary planning over time
    - SHOPPING_ADVISOR: For product purchase advice, price comparisons, product
    recommendations, buying guides, or consumer advice requests
    - FINDAILY: For financial advice, investment recommendations, portfolio analysis,
    stock market insights, crypto analysis, financial planning, daily financial reports
    - NEWSDAILY: For daily news summaries, current events, news analysis, breaking
    news
    - COMPANY_NEWS: For company-specific news, corporate updates, business intelligence
    about specific companies or organizations
    - HOLIDAY_PLANNER: For vacation planning, travel itineraries, destination research
    - BOOK_SUMMARY: For book summaries, reading recommendations, literary analysis,
    book reviews, author information, literature queries, book analysis, tell me about
    book, livre, roman, auteur
    - MEETING_PREP: For meeting preparation, agenda creation, research for meetings
    - And so on for other categories...
    Pay special attention to keywords like:
    - "menu", "weekly", "planner", "planning", "multiple recipes", "shopping list"
    → MENU
    - "recipe", "dish", "cooking technique", "ingredient", "single meal", "risotto"
    → COOKING
    - "achat", "acheter", "conseil", "prix", "comparaison", "recommandation", "produit"
    → SHOPPING_ADVISOR
    - "financier", "finance", "investissement", "bourse", "crypto", "portefeuille",
    "conseil financier"
    → FINDAILY
    - "actualités générales", "nouvelles générales", "general news", "événements", "journal", "information"
    → NEWSDAILY
    - "company news", "corporate news", "news for company", "enterprise news", "business updates", "company updates"
    → COMPANY_NEWS
    - "book", "livre", "roman", "auteur", "author", "tell me about",  → BOOK_SUMMARY
    - "saint", "saint du jour", "daily saint", "saint daily"
    → SAINT
    - "poem", "poème", "poetry", "poésie"
    → POEM
    Provide your final classification decision along with a brief explanation
    of your reasoning.
  expected_output: >
    CATEGORY_NAME
    Where CATEGORY_NAME is one of the provided category options. Your response
    must start with the category name on the first line.
  agent: classifier
  output_file: output/classify/decision.md
