name: CI Tests and Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: create env file
      run: |
         touch .env
         printf '%s\n' "BASE_URL=${{ secrets.BASE_URL }}" >> .env
         printf '%s\n' "RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY }}" >> .env
         printf '%s\n' "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
         printf '%s\n' "OPENAI_MODEL_NAME=${{ secrets.OPENAI_MODEL_NAME }}" >> .env
         printf '%s\n' "COMPOSIO_API_KEY=${{ secrets.COMPOSIO_API_KEY }}" >> .env
         printf '%s\n' "MAIL=${{ secrets.MAIL }}" >> .env

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install the latest version of uv and activate the environment
      uses: astral-sh/setup-uv@v8
      with:
        activate-environment: true
        enable-cache: true
        prune-cache: false

    - name: Install dependencies using Makefile
      run: make dev

    - name: Run linting checks using Makefile
      run: make lint

    - name: Run type checking with mypy
      run: uv run mypy src/epic_news

    - name: Run tests with coverage using Makefile
      run: make coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: fjacquet/epic_news
        fail_ci_if_error: false
