name: CI Tests and Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        envkey_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        envkey_OPENAI_MODEL_NAME: ${{ secrets.OPENAI_MODEL_NAME }}
        envkey_MAIL: ${{ secrets.MAIL }}
        file_name: .env
        fail_on_empty: false
        sort_keys: false  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install the latest version of uv and activate the environment
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
        enable-cache: true
        prune-cache: false

    
    - name: Install project dependencies with uv
      run: |
        uv sync -U
    
    - name: Run tests with coverage
      run: |
        uv run pytest tests/ --cov=src --cov-report=xml --cov-report=term
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: false
    
    - name: Run ruff linter
      run: |
        uv run ruff check .
    
    - name: Run ruff formatter check
      run: |
        uv run ruff format --check .
