company_core_info:
  description: >
    Research and document core information about {company}, including:
    - Full legal name and any parent/subsidiary relationships
    - Year founded and headquarters location
    - Industry classification and primary business activities
    - Size metrics (employees, revenue, market cap if public)
    - Corporate structure and ownership
    - Mission statement and core values
    
    Use the RAG tools to save your findings for later use by other agents.
    Format your findings in a clear, structured, and comprehensive Markdown document, ensuring all relevant details are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document containing all core information about {company},
    with proper formatting, headings, and organization. The report should be as detailed and extensive as possible.
    Save your findings to the RAG database for use by other agents.
  agent: company_profiler
  output_file: output/osint/{company}_core_info.md

company_history:
  description: >
    Research and document the history of {company}, including:
    - Key milestones and founding story
    - Major pivots or strategic shifts
    - Acquisitions and mergers
    - Leadership changes
    - Major product launches
    - Significant challenges or controversies
    
    Use the RAG tools to retrieve any relevant information already collected
    and save your findings for later use by other agents.
    Format your findings in a clear, structured, and comprehensive Markdown document, ensuring all relevant details are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document detailing the history of {company},
    with proper formatting, headings, and organization. The report should be as detailed and extensive as possible.
    Save your findings to the RAG database for use by other agents.
  agent: company_profiler
  output_file: output/osint/{company}_history.md

company_financials:
  description: >
    Analyze the financial performance of {company}, including:
    - Revenue and profit trends (3-5 years if available)
    - Key financial ratios
    - Funding rounds or public offering information
    - Major investors
    - Debt structure
    - Recent financial news
    
    Use the RAG tools to retrieve any relevant information already collected
    and save your findings for later use by other agents.
    Format your findings in a clear, structured, and comprehensive Markdown document, ensuring all relevant details are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document analyzing the financial performance of {company},
    with proper formatting, headings, and organization. The report should be as detailed and extensive as possible.
    Save your findings to the RAG database for use by other agents.
  agent: company_profiler
  output_file: output/osint/{company}_financials.md

company_market_position:
  description: >
    Evaluate the market position of {company}, including:
    - Market share and competitive landscape
    - Key competitors and comparative advantages
    - Industry trends affecting the company
    - Growth opportunities and challenges
    - Recent market developments
    
    Use the RAG tools to retrieve any relevant information already collected
    and save your findings for later use by other agents.
    Format your findings in a clear, structured, and comprehensive Markdown document, ensuring all relevant details are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document evaluating the market position of {company},
    with proper formatting, headings, and organization. The report should be as detailed and extensive as possible.
    Save your findings to the RAG database for use by other agents.
  agent: company_profiler
  output_file: output/osint/{company}_market_position.md

company_products_services:
  description: >
    Document the products and services offered by {company}, including:
    - Core product/service lines
    - Recent launches or discontinued offerings
    - Pricing strategy if available
    - Customer segments served
    - Product development pipeline
    - Reviews and customer sentiment
    
    Use the RAG tools to retrieve any relevant information already collected
    and save your findings for later use by other agents.
    Format your findings in a clear, structured, and comprehensive Markdown document, ensuring all relevant details are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document detailing the products and services of {company},
    with proper formatting, headings, and organization. The report should be as detailed and extensive as possible.
    Save your findings to the RAG database for use by other agents.
  agent: company_profiler
  output_file: output/osint/{company}_products_services.md

company_management:
  description: >
    Research and analyze the management team of {company}, including:
    - Key executives and their backgrounds
    - Board of directors
    - Management style and corporate culture
    - Leadership changes and succession planning
    - Executive compensation if available
    
    Use the RAG tools to retrieve any relevant information already collected
    and save your findings for later use by other agents.
    Format your findings in a clear, structured, and comprehensive Markdown document, ensuring all relevant details are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document analyzing the management team of {company},
    with proper formatting, headings, and organization. The report should be as detailed and extensive as possible.
    Save your findings to the RAG database for use by other agents.
  agent: company_profiler
  output_file: output/osint/{company}_management.md

company_legal_compliance:
  description: >
    Research and document legal and regulatory aspects of {company}, including:
    - Regulatory framework governing the company
    - Compliance history
    - Ongoing or past litigation
    - Regulatory filings
    - Industry-specific compliance requirements
    
    Use the RAG tools to retrieve any relevant information already collected
    and save your findings for later use by other agents.
    Format your findings in a clear, structured, and comprehensive Markdown document, ensuring all relevant details are included for a precise and extensive final report.
  expected_output: >
    A comprehensive Markdown document detailing the legal and regulatory aspects of {company},
    with proper formatting, headings, and organization. The report should be as detailed and extensive as possible.
    Save your findings to the RAG database for use by other agents.
  agent: company_profiler
  output_file: output/osint/{company}_legal_compliance.md