---
company_core_info:
  description: >
    Research and document core information about {company}, including:
    - Full legal name and any parent/subsidiary relationships
    - Year founded and headquarters location
    - Industry classification and primary business activities
    - Size metrics (employees, revenue, market cap if public)
    - Corporate structure and ownership
    - Mission statement and core values
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object containing all core information about {company}.
    The JSON should be well-structured with appropriate keys and values.
  agent: company_researcher
  output_file: "output/osint/{company}_core_info.json"
company_history:
  description: >
    Research and document the history of {company}, including:
    - Key milestones and founding story
    - Major pivots or strategic shifts
    - Acquisitions and mergers
    - Leadership changes
    - Major product launches
    - Significant challenges or controversies
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object detailing the history of {company}.
    The JSON should be well-structured with appropriate keys and values.
  agent: company_researcher
  output_file: "output/osint/{company}_history.json"
company_financials:
  description: >
    Analyze the financial performance of {company}, including:
    - Revenue and profit trends (3-5 years if available)
    - Key financial ratios
    - Funding rounds or public offering information
    - Major investors
    - Debt structure
    - Recent financial news
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object analyzing the financial performance of {company}.
    The JSON should be well-structured with appropriate keys and values.
  agent: company_researcher
  output_file: "output/osint/{company}_financials.json"
company_market_position:
  description: >
    Evaluate the market position of {company}, including:
    - Market share and competitive landscape
    - Key competitors and comparative advantages
    - Industry trends affecting the company
    - Growth opportunities and challenges
    - Recent market developments
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object evaluating the market position of {company}.
    The JSON should be well-structured with appropriate keys and values.
  agent: company_researcher
  output_file: "output/osint/{company}_market_position.json"
company_products_services:
  description: >
    Document the products and services offered by {company}, including:
    - Core product/service lines
    - Recent launches or discontinued offerings
    - Pricing strategy if available
    - Customer segments served
    - Product development pipeline
    - Reviews and customer sentiment
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object detailing the products and services of {company}.
    The JSON should be well-structured with appropriate keys and values.
  agent: company_researcher
  output_file: "output/osint/{company}_products_services.json"
company_management:
  description: >
    Research and analyze the management team of {company}, including:
    - Key executives and their backgrounds
    - Board of directors
    - Management style and corporate culture
    - Leadership changes and succession planning
    - Executive compensation if available
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object analyzing the management team of {company}.
    The JSON should be well-structured with appropriate keys and values.
  agent: company_researcher
  output_file: "output/osint/{company}_management.json"
company_legal_compliance:
  description: >
    Research and document legal and regulatory aspects of {company}, including:
    - Regulatory framework governing the company
    - Compliance history
    - Ongoing or past litigation
    - Regulatory filings
    - Industry-specific compliance requirements
    Format your findings as a structured JSON object.
  expected_output: >
    A comprehensive JSON object detailing the legal and regulatory aspects of
    {company}.
    The JSON should be well-structured with appropriate keys and values.
  agent: company_researcher
  output_file: "output/osint/{company}_legal_compliance.json"
format_report_task:
  description: >
    Format the comprehensive company profile report for {company}.
    This task will take all the previously gathered information and format it into
    a single, comprehensive, and well-structured data object.
  expected_output: >
    A comprehensive data object containing all the information about {company}, conforming
    to the CompanyProfileReport Pydantic model.
  agent: company_reporter
  output_file: "output/osint/{company}_profile.json"
